apiVersion: v1
externalServicesDeclarations:
- name: svcsdsprometheusui
  type: loadBalancer
  hostnameChartField: svcsdsprometheusui.hostname
  loadBalancerPortChartField: svcsdsprometheusui.port
  enabled: false
  enabledChartField: svcsdsprometheusui.enabled
  label: Prometheus UI
  description: Port to access the Prometheus UI over a Load Balancer
- name: svcsdsgrafanaui
  type: loadBalancer
  hostnameChartField: svcsdsgrafanaui.hostname
  loadBalancerPortChartField: svcsdsgrafanaui.port
  enabled: false
  enabledChartField: svcsdsgrafanaui.enabled
  label: Grafana UI
  description: Port to access the Grafana UI over a Load Balancer
endpoints:
- title: Prometheus UI
  group: Developer
  description: Open the Prometheus UI in your browser
  type: browsing
  url: http://{externalService.host}:{externalService.port}/
  contexts:
  - portal
  - manage
  visibility: external
  presentation: link
  externalService: svcsdsprometheusui
- title: Grafana UI
  group: Developer
  description: Open the Grafana UI in your browser
  type: browsing
  #url: http://{externalService.host}:{externalService.port}/
  url: http://{externalService.host}:80/
  contexts:
  - portal
  - manage
  visibility: external
  presentation: link
  externalService: svcsdsgrafanaui
  